# Site settings
title: Vistories
email: contact@caleydo.org
description: "Reproducibility, Collaboration, and Communication for Exploratory and Visual Analyses"
baseurl: ""
url: "http://vistories.org"
twitter_username: caleydo_org
github_username:  caleydo
youtube_username: caleydotugraz
facebook_page: Caleydo/110550618994500
license_url: https://raw.githubusercontent.com/vistory/vistories.github.io/LICENSE
safe: false
lsi: false
google_analytics: "'UA-45998043-3'"
use_analytics: true
server_url: http://demo.caleydo.org

gems:
  - jekyll-redirect-from

# Build settings

permalink: pretty
sass:
  sass_dir: _sass
# exclude from build
exclude: ["README.md", ".idea/", "Gemfile", "Gemfile.lock", "rvm.env"]

# code highlighter
#highlighter: rouge

# Collections
collections:
  vistories:
    output: true
    permalink: /v/:path
